platform :ios, '16.2'

target 'CredlyDeveloperChallenge' do
  use_frameworks!

  # Pods for CredlyDeveloperChallenge
	pod 'Alamofire', '~> 5.6'
	pod 'SwiftyJSON', '~> 5.0'

  target 'CredlyDeveloperChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CredlyDeveloperChallengeUITests' do
    # Pods for testing
  end

end
